export type FloodKategori = 'hayvanlar' | 'ciftlik' | 'dinozorlar' | 'kultur' | 'kahramanlar' | 'masallar';

export type FloodSahne = {
  id: string;
  baslik: string;
  kategori: FloodKategori;
  src: string;
};

export const FLOOD_KATEGORI_AD: Record<FloodKategori, string> = {
  hayvanlar: 'Hayvanlar',
  ciftlik: 'Çiftlik',
  dinozorlar: 'Dinozorlar',
  kultur: 'Kültür',
  kahramanlar: 'Kahramanlar',
  masallar: 'Masallar',
};

export const FLOOD_SAHNELER: FloodSahne[] = [
  { id: 'fil-vahsi', baslik: 'Fil (vahşi)', kategori: 'hayvanlar', src: '/boyama-yeni/fil-vahsi.png' },
  { id: 'kopek-park', baslik: 'Köpek (park)', kategori: 'hayvanlar', src: '/boyama-yeni/kopek-park.png' },
  { id: 'dino-orman', baslik: 'Dino (orman)', kategori: 'dinozorlar', src: '/boyama-yeni/dino-orman.png' },
  { id: 'dino-poz', baslik: 'Dino (poz)', kategori: 'dinozorlar', src: '/boyama-yeni/dinozorlar/poz.png' },
  { id: 'dino-arkadaslar', baslik: 'Dino ve arkadaşları', kategori: 'dinozorlar', src: '/boyama-yeni/dinozorlar/arkadaslar.png' },
  { id: 'dino-asci', baslik: 'Aşçı dino', kategori: 'dinozorlar', src: '/boyama-yeni/dinozorlar/asci.png' },
  { id: 'dino-bahce', baslik: 'Sihirli bahçe', kategori: 'dinozorlar', src: '/boyama-yeni/dinozorlar/bahce.png' },
  { id: 'dino-bilim', baslik: 'Bilim şenliği', kategori: 'dinozorlar', src: '/boyama-yeni/dinozorlar/bilim.png' },
  { id: 'dino-ciftlik', baslik: 'Dino çiftlikte', kategori: 'dinozorlar', src: '/boyama-yeni/dinozorlar/ciftlik.png' },
  { id: 'dino-cimen', baslik: 'Çimde oyun', kategori: 'dinozorlar', src: '/boyama-yeni/dinozorlar/cimen.png' },
  { id: 'dino-col', baslik: 'Çöl', kategori: 'dinozorlar', src: '/boyama-yeni/dinozorlar/col.png' },
  { id: 'dino-dogum-gunu', baslik: 'Doğum günü', kategori: 'dinozorlar', src: '/boyama-yeni/dinozorlar/dogum-gunu.png' },
  { id: 'dino-gokkusagi', baslik: 'Gökkuşağı', kategori: 'dinozorlar', src: '/boyama-yeni/dinozorlar/gokkusagi.png' },
  { id: 'dino-hayvanat', baslik: 'Hayvanat bahçesi', kategori: 'dinozorlar', src: '/boyama-yeni/dinozorlar/hayvanat.png' },
  { id: 'dino-kar-kuresi', baslik: 'Kar küresi', kategori: 'dinozorlar', src: '/boyama-yeni/dinozorlar/kar-kuresi.png' },
  { id: 'dino-kasif', baslik: 'Kaşif', kategori: 'dinozorlar', src: '/boyama-yeni/dinozorlar/kasif.png' },
  { id: 'dino-kayip-sehir', baslik: 'Kayıp şehir', kategori: 'dinozorlar', src: '/boyama-yeni/dinozorlar/kayip-sehir.png' },
  { id: 'dino-kis', baslik: 'Kış', kategori: 'dinozorlar', src: '/boyama-yeni/dinozorlar/kis.png' },
  { id: 'dino-korsan', baslik: 'Korsan', kategori: 'dinozorlar', src: '/boyama-yeni/dinozorlar/korsan.png' },
  { id: 'dino-kutuphane', baslik: 'Kütüphane', kategori: 'dinozorlar', src: '/boyama-yeni/dinozorlar/kutuphane.png' },
  { id: 'dino-lunapark', baslik: 'Lunapark', kategori: 'dinozorlar', src: '/boyama-yeni/dinozorlar/lunapark.png' },
  { id: 'dino-masal', baslik: 'Masal şövalyesi', kategori: 'dinozorlar', src: '/boyama-yeni/dinozorlar/masal.png' },
  { id: 'dino-muzik', baslik: 'Müzisyen', kategori: 'dinozorlar', src: '/boyama-yeni/dinozorlar/muzik.png' },
  { id: 'dino-okul', baslik: 'Okul', kategori: 'dinozorlar', src: '/boyama-yeni/dinozorlar/okul.png' },
  { id: 'dino-plaj', baslik: 'Plaj', kategori: 'dinozorlar', src: '/boyama-yeni/dinozorlar/plaj.png' },
  { id: 'dino-rock', baslik: 'Rock grubu', kategori: 'dinozorlar', src: '/boyama-yeni/dinozorlar/rock.png' },
  { id: 'dino-sehir', baslik: 'Şehir', kategori: 'dinozorlar', src: '/boyama-yeni/dinozorlar/sehir.png' },
  { id: 'dino-sualti', baslik: 'Su altı', kategori: 'dinozorlar', src: '/boyama-yeni/dinozorlar/sualti.png' },
  { id: 'dino-super-kahraman', baslik: 'Süper kahraman', kategori: 'dinozorlar', src: '/boyama-yeni/dinozorlar/super-kahraman.png' },
  { id: 'dino-uzay', baslik: 'Uzay', kategori: 'dinozorlar', src: '/boyama-yeni/dinozorlar/uzay-1.png' },
  { id: 'dino-zaman', baslik: 'Zaman makinesi', kategori: 'dinozorlar', src: '/boyama-yeni/dinozorlar/zaman.png' },

  { id: 'ciftlik-inek', baslik: 'İnek', kategori: 'ciftlik', src: '/boyama-yeni/ciftlik/inek.png' },
  { id: 'ciftlik-ordekler', baslik: 'Ördekler', kategori: 'ciftlik', src: '/boyama-yeni/ciftlik/ordekler.png' },
  { id: 'ciftlik-traktor', baslik: 'Traktör', kategori: 'ciftlik', src: '/boyama-yeni/ciftlik/traktor.png' },
  { id: 'ciftlik-isler', baslik: 'Çiftlik işleri', kategori: 'ciftlik', src: '/boyama-yeni/ciftlik/isler.png' },
  { id: 'ciftlik-panayir', baslik: 'Köy panayırı', kategori: 'ciftlik', src: '/boyama-yeni/ciftlik/panayir.png' },
  { id: 'ciftlik-piknik', baslik: 'Çiftlik pikniği', kategori: 'ciftlik', src: '/boyama-yeni/ciftlik/piknik.png' },
  { id: 'ciftlik-mevsim-1', baslik: 'Çiftlik mevsimleri', kategori: 'ciftlik', src: '/boyama-yeni/ciftlik/mevsim-1.png' },
  { id: 'ciftlik-mevsim-2', baslik: 'Çiftlik mevsimleri 2', kategori: 'ciftlik', src: '/boyama-yeni/ciftlik/mevsim-2.png' },

  { id: 'alpaka', baslik: 'Alpaka', kategori: 'hayvanlar', src: '/boyama-yeni/hayvanlar/alpaka.png' },
  { id: 'ayi', baslik: 'Ayı', kategori: 'hayvanlar', src: '/boyama-yeni/hayvanlar/ayi.png' },
  { id: 'kunduz', baslik: 'Kunduz (köprü)', kategori: 'hayvanlar', src: '/boyama-yeni/hayvanlar/kunduz.png' },
  { id: 'aslan', baslik: 'Aslan', kategori: 'hayvanlar', src: '/boyama-yeni/hayvanlar/aslan.png' },
  { id: 'flamingo', baslik: 'Flamingo', kategori: 'hayvanlar', src: '/boyama-yeni/hayvanlar/flamingo.png' },
  { id: 'kanguru', baslik: 'Kanguru', kategori: 'hayvanlar', src: '/boyama-yeni/hayvanlar/kanguru.png' },
  { id: 'kaplan', baslik: 'Kaplan', kategori: 'hayvanlar', src: '/boyama-yeni/hayvanlar/kaplan.png' },
  { id: 'kedi', baslik: 'Kedi', kategori: 'hayvanlar', src: '/boyama-yeni/hayvanlar/kedi.png' },
  { id: 'panda', baslik: 'Panda', kategori: 'hayvanlar', src: '/boyama-yeni/hayvanlar/panda.png' },
  { id: 'rakun', baslik: 'Rakun', kategori: 'hayvanlar', src: '/boyama-yeni/hayvanlar/rakun.png' },
  { id: 'bukalemun', baslik: 'Bukalemun', kategori: 'hayvanlar', src: '/boyama-yeni/hayvanlar/bukalemun.png' },
  { id: 'yunus', baslik: 'Yunus', kategori: 'hayvanlar', src: '/boyama-yeni/hayvanlar/yunus.png' },
  { id: 'ahtapot', baslik: 'Ahtapot', kategori: 'hayvanlar', src: '/boyama-yeni/hayvanlar/ahtapot.png' },
  { id: 'horoz', baslik: 'Horoz', kategori: 'hayvanlar', src: '/boyama-yeni/hayvanlar/horoz.png' },
  { id: 'kaplumbaga', baslik: 'Kaplumbağa', kategori: 'hayvanlar', src: '/boyama-yeni/hayvanlar/kara-kaplumbaga.png' },
  { id: 'hindi', baslik: 'Hindi', kategori: 'hayvanlar', src: '/boyama-yeni/hayvanlar/hindi.png' },
  { id: 'kaplumbaga-yuzme', baslik: 'Kaplumbağa (yüzüyor)', kategori: 'hayvanlar', src: '/boyama-yeni/hayvanlar/kaplumbaga-yuzme.png' },
  { id: 'istiridye', baslik: 'İstiridye', kategori: 'hayvanlar', src: '/boyama-yeni/hayvanlar/istiridye.png' },
  { id: 'kurbaga', baslik: 'Kurbağa', kategori: 'hayvanlar', src: '/boyama-yeni/hayvanlar/kurbaga.png' },
  { id: 'oklu-kirpi', baslik: 'Oklu kirpi', kategori: 'hayvanlar', src: '/boyama-yeni/hayvanlar/oklu-kirpi.png' },

  { id: 'kultur-abd', baslik: 'Özgürlük Heykeli', kategori: 'kultur', src: '/boyama-yeni/kultur/abd.png' },
  { id: 'kultur-avusturya', baslik: 'Avusturya', kategori: 'kultur', src: '/boyama-yeni/kultur/avusturya.png' },
  { id: 'kultur-cin', baslik: 'Çin', kategori: 'kultur', src: '/boyama-yeni/kultur/cin.png' },
  { id: 'kultur-fransa', baslik: 'Fransa', kategori: 'kultur', src: '/boyama-yeni/kultur/fransa.png' },
  { id: 'kultur-guney-afrika', baslik: 'Güney Afrika', kategori: 'kultur', src: '/boyama-yeni/kultur/guney-afrika.png' },
  { id: 'kultur-guney-kore', baslik: 'Güney Kore', kategori: 'kultur', src: '/boyama-yeni/kultur/guney-kore.png' },
  { id: 'kultur-hollanda', baslik: 'Hollanda', kategori: 'kultur', src: '/boyama-yeni/kultur/hollanda.png' },
  { id: 'kultur-isvicre', baslik: 'İsviçre', kategori: 'kultur', src: '/boyama-yeni/kultur/isvicre.png' },
  { id: 'kultur-italya', baslik: 'İtalya', kategori: 'kultur', src: '/boyama-yeni/kultur/italya.png' },
  { id: 'kultur-japonya', baslik: 'Japonya', kategori: 'kultur', src: '/boyama-yeni/kultur/japonya.png' },
  { id: 'kultur-kenya', baslik: 'Kenya', kategori: 'kultur', src: '/boyama-yeni/kultur/kenya.png' },
  { id: 'kultur-meksika', baslik: 'Meksika', kategori: 'kultur', src: '/boyama-yeni/kultur/meksika.png' },
  { id: 'kultur-misir', baslik: 'Mısır', kategori: 'kultur', src: '/boyama-yeni/kultur/misir.png' },
  { id: 'kultur-peru', baslik: 'Peru', kategori: 'kultur', src: '/boyama-yeni/kultur/peru.png' },
  { id: 'kultur-vietnam', baslik: 'Vietnam', kategori: 'kultur', src: '/boyama-yeni/kultur/vietnam.png' },
  { id: 'kultur-yeni-zelanda', baslik: 'Yeni Zelanda', kategori: 'kultur', src: '/boyama-yeni/kultur/yeni-zelanda.png' },
  { id: 'kultur-yunanistan', baslik: 'Yunanistan', kategori: 'kultur', src: '/boyama-yeni/kultur/yunanistan.png' },

  { id: 'kahraman-bilim-ilac', baslik: 'Bilim insanı', kategori: 'kahramanlar', src: '/boyama-yeni/kahramanlar/bilim-ilac.png' },
  { id: 'kahraman-ciftci-lahana', baslik: 'Lahana tarlası', kategori: 'kahramanlar', src: '/boyama-yeni/kahramanlar/ciftci-lahana.png' },
  { id: 'kahraman-ciftci-pirinc', baslik: 'Çiftçi', kategori: 'kahramanlar', src: '/boyama-yeni/kahramanlar/ciftci-pirinc.png' },
  { id: 'kahraman-ciftci-traktor', baslik: 'Traktör', kategori: 'kahramanlar', src: '/boyama-yeni/kahramanlar/ciftci-traktor.png' },
  { id: 'kahraman-cop-park', baslik: 'Park temizliği', kategori: 'kahramanlar', src: '/boyama-yeni/kahramanlar/cop-park.png' },
  { id: 'kahraman-copcu', baslik: 'Çöpçü', kategori: 'kahramanlar', src: '/boyama-yeni/kahramanlar/copcu.png' },
  { id: 'kahraman-gonullu-nehir', baslik: 'Nehir temizliği', kategori: 'kahramanlar', src: '/boyama-yeni/kahramanlar/gonullu-nehir.png' },
  { id: 'kahraman-guvenlik', baslik: 'Güvenlik', kategori: 'kahramanlar', src: '/boyama-yeni/kahramanlar/guvenlik.png' },
  { id: 'kahraman-hastane', baslik: 'Hastane', kategori: 'kahramanlar', src: '/boyama-yeni/kahramanlar/hastane.png' },
  { id: 'kahraman-hemsire-bebek', baslik: 'Hemşire', kategori: 'kahramanlar', src: '/boyama-yeni/kahramanlar/hemsire-bebek.png' },
  { id: 'kahraman-hemsire-kontrol', baslik: 'Hemşire kontrol', kategori: 'kahramanlar', src: '/boyama-yeni/kahramanlar/hemsire-kontrol.png' },
  { id: 'kahraman-insaat', baslik: 'İnşaat', kategori: 'kahramanlar', src: '/boyama-yeni/kahramanlar/insaat.png' },
  { id: 'kahraman-itfaiyeci-arac-2', baslik: 'İtfaiyeci', kategori: 'kahramanlar', src: '/boyama-yeni/kahramanlar/itfaiyeci-arac-2.png' },
  { id: 'kahraman-kurye', baslik: 'Kurye', kategori: 'kahramanlar', src: '/boyama-yeni/kahramanlar/kurye.png' },
  { id: 'kahraman-muhendis', baslik: 'Mühendis', kategori: 'kahramanlar', src: '/boyama-yeni/kahramanlar/muhendis.png' },
  { id: 'kahraman-ogretmen', baslik: 'Öğretmen', kategori: 'kahramanlar', src: '/boyama-yeni/kahramanlar/ogretmen.png' },
  { id: 'kahraman-paramedik-diz', baslik: 'Diz bakımı', kategori: 'kahramanlar', src: '/boyama-yeni/kahramanlar/paramedik-diz.png' },
  { id: 'kahraman-paramedik', baslik: 'Paramedik', kategori: 'kahramanlar', src: '/boyama-yeni/kahramanlar/paramedik.png' },
  { id: 'kahraman-polis-arac', baslik: 'Polis arabası', kategori: 'kahramanlar', src: '/boyama-yeni/kahramanlar/polis-arac.png' },
  { id: 'kahraman-polis', baslik: 'Polis', kategori: 'kahramanlar', src: '/boyama-yeni/kahramanlar/polis.png' },
  { id: 'kahraman-postaci', baslik: 'Postacı', kategori: 'kahramanlar', src: '/boyama-yeni/kahramanlar/postaci.png' },
  { id: 'kahraman-sofor-otobus', baslik: 'Otobüs şoförü', kategori: 'kahramanlar', src: '/boyama-yeni/kahramanlar/sofor-otobus.png' },
  { id: 'kahraman-tamirci', baslik: 'Tamirci', kategori: 'kahramanlar', src: '/boyama-yeni/kahramanlar/tamirci.png' },
  { id: 'kahraman-temizlik-sokak', baslik: 'Sokak temizliği', kategori: 'kahramanlar', src: '/boyama-yeni/kahramanlar/temizlik-sokak.png' },
  { id: 'kahraman-yardim', baslik: 'Yardım', kategori: 'kahramanlar', src: '/boyama-yeni/kahramanlar/yardim.png' },

  { id: 'masal-ankka', baslik: 'Anka kuşu', kategori: 'masallar', src: '/boyama-yeni/masallar/ankka.png' },
  { id: 'masal-ayna-gol', baslik: 'Ayna göl', kategori: 'masallar', src: '/boyama-yeni/masallar/ayna-gol.png' },
  { id: 'masal-buyucu-atolyesi', baslik: 'Büyücü atölyesi', kategori: 'masallar', src: '/boyama-yeni/masallar/buyucu-atolyesi.png' },
  { id: 'masal-buyucu-kutuphane', baslik: 'Büyücü kütüphanesi', kategori: 'masallar', src: '/boyama-yeni/masallar/buyucu-kutuphane.png' },
  { id: 'masal-buyulu-hayvan', baslik: 'Büyülü hayvanlar', kategori: 'masallar', src: '/boyama-yeni/masallar/buyulu-hayvan.png' },
  { id: 'masal-buyulu-kulube', baslik: 'Büyülü kulübe', kategori: 'masallar', src: '/boyama-yeni/masallar/buyulu-kulube.png' },
  { id: 'masal-deniz-kizi', baslik: 'Deniz kızı', kategori: 'masallar', src: '/boyama-yeni/masallar/deniz-kizi.png' },
  { id: 'masal-deniz-yilan', baslik: 'Deniz atı', kategori: 'masallar', src: '/boyama-yeni/masallar/deniz-yilan.png' },
  { id: 'masal-dev-bahce', baslik: 'Dev bahçesi', kategori: 'masallar', src: '/boyama-yeni/masallar/dev-bahce.png' },
  { id: 'masal-dev-kale', baslik: 'Dev kalesi', kategori: 'masallar', src: '/boyama-yeni/masallar/dev-kale.png' },
  { id: 'masal-ejderha-sovalye', baslik: 'Ejderha ve şövalye', kategori: 'masallar', src: '/boyama-yeni/masallar/ejderha-sovalye.png' },
  { id: 'masal-goblin-pazar', baslik: 'Goblin pazarı', kategori: 'masallar', src: '/boyama-yeni/masallar/goblin-pazar.png' },
  { id: 'masal-hali-fabrika', baslik: 'Halı fabrikası', kategori: 'masallar', src: '/boyama-yeni/masallar/hali-fabrika.png' },
  { id: 'masal-kale-macera', baslik: 'Kale', kategori: 'masallar', src: '/boyama-yeni/masallar/kale-macera.png' },
  { id: 'masal-karlar-kralicesi', baslik: 'Karlar kraliçesi', kategori: 'masallar', src: '/boyama-yeni/masallar/karlar-kralicesi.png' },
  { id: 'masal-kristal-magara', baslik: 'Kristal mağara', kategori: 'masallar', src: '/boyama-yeni/masallar/kristal-magara.png' },
  { id: 'masal-masal-balo', baslik: 'Masal balosu', kategori: 'masallar', src: '/boyama-yeni/masallar/masal-balo.png' },
  { id: 'masal-peri-anne', baslik: 'Peri', kategori: 'masallar', src: '/boyama-yeni/masallar/peri-anne.png' },
  { id: 'masal-peri-halka', baslik: 'Peri halkası', kategori: 'masallar', src: '/boyama-yeni/masallar/peri-halka.png' },
  { id: 'masal-peri-koyu', baslik: 'Peri köyü', kategori: 'masallar', src: '/boyama-yeni/masallar/peri-koyu.png' },
  { id: 'masal-saat-kulesi', baslik: 'Saat kulesi', kategori: 'masallar', src: '/boyama-yeni/masallar/saat-kulesi.png' },
  { id: 'masal-sihirli-bahce', baslik: 'Sihirli bahçe', kategori: 'masallar', src: '/boyama-yeni/masallar/sihirli-bahce.png' },
  { id: 'masal-trol-kopru', baslik: 'Trol köprüsü', kategori: 'masallar', src: '/boyama-yeni/masallar/trol-kopru.png' },
  { id: 'masal-unikorn', baslik: 'Unicorn', kategori: 'masallar', src: '/boyama-yeni/masallar/unikorn.png' },
  { id: 'masal-yildiz-balo', baslik: 'Yıldız balosu', kategori: 'masallar', src: '/boyama-yeni/masallar/yildiz-balo.png' },
];
